# .github/workflows/deploy.yml
# GitHub Actions workflow for Simple Hardware Calculator
name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write  # maybe too loosen
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    # env:
    #   SUBDIR: llmcalc

    steps:
      - uses: actions/checkout@v4

      # 1. Node (pick a real version)
      - uses: actions/setup-node@v4
        with:
          node-version: 22          # or 20 for LTS
      #     cache: npm               # enable pnpm store cache

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build -- --base=/${{ github.event.repository.name }}/

      # Configure Pages metadata (required by Pages deployments)
      - uses: actions/configure-pages@v5   # current major version

      # Deploy
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          destination_dir: .
          force_orphan: true